# -*- coding: utf-8 -*-
"""krishi visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hKT0EIAAM9jfOSMjRNWsg0M1E3hpYxTJ
"""

# Install required libraries (if not already)
!pip install matplotlib seaborn pandas

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = pd.read_csv("labeled_dataset.csv")

# --- 1. Distribution of Labels (Pie Chart) ---
label_counts = df["label"].value_counts()

plt.figure(figsize=(6,6))
plt.pie(label_counts, labels=label_counts.index, autopct='%1.1f%%', startangle=140, colors=sns.color_palette("Set2"))
plt.title("Distribution of Agricultural Categories")
plt.show()

# --- 2. Bar Plot of Labels ---
plt.figure(figsize=(8,5))
sns.barplot(x=label_counts.index, y=label_counts.values, palette="Set2")
plt.xlabel("Category")
plt.ylabel("Number of Entries")
plt.title("Entries per Category")
plt.xticks(rotation=90)
plt.show()

# --- 3. Document Length Distribution ---
df["Content_Length"] = df["Content"].astype(str).apply(lambda x: len(x.split()))

plt.figure(figsize=(8,5))
sns.histplot(df["Content_Length"], bins=30, kde=True, color="skyblue")
plt.xlabel("Number of Words")
plt.ylabel("Frequency")
plt.title("Distribution of Document Lengths")
plt.show()